<?php

namespace Config;

/**
 * Historical placed-candidate testimonials captured in the legacy
 * Candidate Testimonial Google Form in 2025. The public copy below is
 * grammar-cleaned only; original answers are preserved for admin review.
 */
class HistoricalTestimonials
{
    public static function all(): array
    {
        return [
            [
                'client_name' => 'Shefi Gupta',
                'name' => 'Shefi Gupta',
                'company' => 'Marriott International',
                'designation' => 'Senior Revenue Manager',
                'comment' => 'HiredNext acted as a bridge between the company and me, making the entire process much easier and efficient. They helped me move into an industry I may not have considered otherwise. I would recommend them, especially for their responsiveness.',
                'original_comment' => "They acted as a bridge between the company and me which made the whole process quite easier. | Efficient process | Helped me moving into the industry which I wouldn't have tried ever. | Yes | Responsiveness | Job satisfaction: 5/5",
                'rating' => 5,
                'project_type' => 'Candidate Journey',
                'proof_type' => 'Placed Candidate Story',
                'source_label' => 'Candidate Testimonial Form · 16 Jul 2025',
                'source_url' => '',
                'linkedin_url' => 'https://www.linkedin.com/in/shefigupta/',
                'submitter_email' => 'shefigupta89@gmail.com',
                'submitted_via' => 'legacy_candidate_testimonial_form',
                'relationship_type' => 'placed_candidate',
                'placement_role' => 'Senior Revenue Manager · Marriott International',
                'placement_location' => 'Bengaluru',
                'placement_year' => '2025',
                'placement_date' => '2025-04-03',
                'status' => 'active',
                'sort_order' => 10,
                'created_at' => '2025-07-16 11:51:27',
            ],
            [
                'client_name' => 'Shripad Tokekar',
                'name' => 'Shripad Tokekar',
                'company' => 'PDS Limited',
                'designation' => 'Assistant Manager Finance',
                'comment' => 'HiredNext was supportive, cooperative and highly responsive throughout my placement journey. The process had a positive impact on my career growth, and I would recommend HiredNext to other professionals looking for the right opportunity.',
                'original_comment' => 'Nice support and cooperative | Nice placement hub | Nice impact on my carrier hired enable nice for my growth | They are nice and cooperative people | Responsiveness | Job satisfaction: 5/5',
                'rating' => 5,
                'project_type' => 'Candidate Journey',
                'proof_type' => 'Placed Candidate Story',
                'source_label' => 'Candidate Testimonial Form · 16 Jul 2025',
                'source_url' => '',
                'linkedin_url' => '',
                'submitter_email' => 'shripadtokekar07@gmail.com',
                'submitted_via' => 'legacy_candidate_testimonial_form',
                'relationship_type' => 'placed_candidate',
                'placement_role' => 'Assistant Manager Finance · PDS Limited',
                'placement_location' => 'Mumbai',
                'placement_year' => '2025',
                'placement_date' => '2025-03-10',
                'status' => 'active',
                'sort_order' => 20,
                'created_at' => '2025-07-16 11:57:47',
            ],
            [
                'client_name' => 'Ranjan',
                'name' => 'Ranjan',
                'company' => 'PDS Group',
                'designation' => 'Merchandising Manager',
                'comment' => 'Thanks to HiredNext, I secured a great role with a reputed company that aligns with my career goals. Their guidance, structured approach and timely updates kept me focused and confident at every stage of the process. I would absolutely recommend them.',
                'original_comment' => 'Thanks to their efforts, i have secured a great job profile with a reputed company that aligns well with my career goal. | I’m truly grateful for the support provided by Hirednext throughout my job search journey. Their guidance, structured approach, and timely updates helped me stay focused and confident at every stage of the process. | It is fantastic. | Yes,,Sure.. You will get your dream here. | Responsiveness | Job satisfaction: 5/5',
                'rating' => 5,
                'project_type' => 'Candidate Journey',
                'proof_type' => 'Placed Candidate Story',
                'source_label' => 'Candidate Testimonial Form · 16 Jul 2025',
                'source_url' => '',
                'linkedin_url' => '',
                'submitter_email' => 'designer2rs@gmail.com',
                'submitted_via' => 'legacy_candidate_testimonial_form',
                'relationship_type' => 'placed_candidate',
                'placement_role' => 'Merchandising Manager · PDS Group',
                'placement_location' => 'Gurgaon',
                'placement_year' => '2025',
                'placement_date' => '2025-07-07',
                'status' => 'active',
                'sort_order' => 30,
                'created_at' => '2025-07-16 22:48:03',
            ],
            [
                'client_name' => 'Aman Yadav',
                'name' => 'Aman Yadav',
                'company' => 'PDS',
                'designation' => 'Compliance Auditor',
                'comment' => 'The HiredNext process was impressive. The recruiting team was cooperative and supportive throughout the joining process, and their understanding of the candidate’s role and resume stood out. The move has supported continued learning and growth.',
                'original_comment' => 'Impressive | Impressive | Continues learning and growth | The recruiting team is very cooperative and supporting for whole the joining process | Candidate role/resume understanding | Job satisfaction: 5/5',
                'rating' => 5,
                'project_type' => 'Candidate Journey',
                'proof_type' => 'Placed Candidate Story',
                'source_label' => 'Candidate Testimonial Form · 17 Jul 2025',
                'source_url' => '',
                'linkedin_url' => '',
                'submitter_email' => 'amanyadav1976@icloud.com',
                'submitted_via' => 'legacy_candidate_testimonial_form',
                'relationship_type' => 'placed_candidate',
                'placement_role' => 'Compliance Auditor · PDS',
                'placement_location' => 'Gurgaon',
                'placement_year' => '2025',
                'placement_date' => '2025-05-06',
                'status' => 'active',
                'sort_order' => 40,
                'created_at' => '2025-07-17 12:11:11',
            ],
            [
                'client_name' => 'Shyamlee',
                'name' => 'Shyamlee',
                'company' => 'Buana Samudra Lestari',
                'designation' => 'Business Head',
                'comment' => 'I would rate my experience 10/10. The process was quick, hassle-free and completely clear, with no issues or hiccups. The role gave me tremendous exposure and career growth, and I would absolutely recommend HiredNext for the ownership and responsiveness shown throughout the process.',
                'original_comment' => 'I would rate my experience 10/10 it was soo quick and hassel free, zero issues or hick ups in the entire process and with complete clarity | Replied above | Got tremendous exposure and career growth | Yes ofcourse, they do complete reiki before placing any candidate and take complete ownership from both sides | Responsiveness | Job satisfaction: 5/5',
                'rating' => 5,
                'project_type' => 'Candidate Journey',
                'proof_type' => 'Placed Candidate Story',
                'source_label' => 'Candidate Testimonial Form · 17 Jul 2025',
                'source_url' => '',
                'linkedin_url' => '',
                'submitter_email' => 'shyamlee.s16@gmail.com',
                'submitted_via' => 'legacy_candidate_testimonial_form',
                'relationship_type' => 'placed_candidate',
                'placement_role' => 'Business Head · Buana Samudra Lestari',
                'placement_location' => 'Jakarta, Indonesia',
                'placement_year' => '2017',
                'placement_date' => '2017-02-10',
                'status' => 'active',
                'sort_order' => 50,
                'created_at' => '2025-07-17 22:28:12',
            ],
            [
                'client_name' => 'Nidhi Pande',
                'name' => 'Nidhi Pande',
                'company' => 'PDS Limited',
                'designation' => 'Senior Executive',
                'comment' => 'HiredNext introduced me to the right vacancy and supported me through the interview process. Their help was instrumental in getting offers from good companies, and their responsiveness stood out.',
                'original_comment' => 'Really helpful to get the offers from good companies. | Introduced me to this vacancy and interview process | Responsiveness',
                'rating' => 0,
                'project_type' => 'Candidate Journey',
                'proof_type' => 'Placed Candidate Story',
                'source_label' => 'Candidate Testimonial Form · 23 Jul 2025',
                'source_url' => 'https://drive.google.com/open?id=1-FQz0t_zslDy1qiKp55yJornDXywhBkJ',
                'linkedin_url' => 'https://www.linkedin.com/in/nidhi-pande-285432230',
                'evidence_image_url' => 'https://drive.google.com/open?id=1-FQz0t_zslDy1qiKp55yJornDXywhBkJ',
                'submitter_email' => 'csnidhipande07@gmail.com',
                'submitted_via' => 'legacy_candidate_testimonial_form',
                'relationship_type' => 'placed_candidate',
                'placement_role' => 'Senior Executive · PDS Limited',
                'placement_location' => 'Mumbai',
                'placement_year' => '2025',
                'placement_date' => '2025-04-07',
                'status' => 'active',
                'sort_order' => 60,
                'created_at' => '2025-07-23 20:22:31',
            ],
            [
                'client_name' => 'Md. Arif Uddin',
                'name' => 'Md. Arif Uddin',
                'company' => 'Victory Time International Ltd.',
                'designation' => 'Executive Accounts',
                'comment' => 'HiredNext supported my placement journey with relevant opportunities, career guidance, resume and interview support, and timely updates. The process felt smoother and more organised and helped me secure a role aligned with my career goals.',
                'original_comment' => 'HiredNext is a leading platform that bridges the gap between job seekers and employers by providing smart, AI-driven recruitment solutions... | HiredNext has played a significant role in my placement journey by providing access to relevant job opportunities and personalized career guidance... Thanks to their support, I was able to secure a position that aligns with my career goals. I’m truly grateful for the valuable assistance they provided throughout the process. | Global Reach',
                'rating' => 0,
                'project_type' => 'Candidate Journey',
                'proof_type' => 'Placed Candidate Story',
                'source_label' => 'Candidate Testimonial Form · 8 Aug 2025',
                'source_url' => 'https://drive.google.com/open?id=1VHqk_Z7fFzQFfkyhAcHWa6joHn1w9d5F',
                'linkedin_url' => '',
                'evidence_image_url' => 'https://drive.google.com/open?id=1VHqk_Z7fFzQFfkyhAcHWa6joHn1w9d5F',
                'submitter_email' => 'sajan.arif4@gmail.com',
                'submitted_via' => 'legacy_candidate_testimonial_form',
                'relationship_type' => 'placed_candidate',
                'placement_role' => 'Executive Accounts · Victory Time International Ltd.',
                'placement_location' => 'Baridhara DOHS',
                'placement_year' => '2025',
                'placement_date' => '2025-06-19',
                'status' => 'active',
                'sort_order' => 70,
                'created_at' => '2025-08-08 10:21:28',
            ],
        ];
    }
}
