<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<section class="relative pt-32 pb-20 bg-primary text-white overflow-hidden"><div class="max-w-[1180px] mx-auto px-4 sm:px-8"><div class="max-w-4xl"><div class="text-gold text-xs font-black uppercase tracking-[0.28em] mb-5">Limited Advisory Access</div><h1 class="text-4xl md:text-6xl font-serif font-bold leading-tight mb-6">Researched career strategy and confidential CXO advisory.</h1><p class="text-lg md:text-xl text-white/75 max-w-3xl">These are prepared advisory sessions, not introductory calls. Your CV, LinkedIn profile, objective and stated challenge are reviewed before the conversation. Only four advisory appointments are released each month.</p></div></div></section>
<section class="py-20 bg-gray-50"><div class="max-w-[1180px] mx-auto px-4 sm:px-8">
<div class="grid lg:grid-cols-2 gap-6 mb-10"><article id="career-strategy" class="rounded-[2rem] border border-gray-200 bg-white p-8"><div class="text-accent text-sm font-black mb-2">₹6,500 · 60 MINUTES</div><h2 class="text-3xl font-serif font-bold text-primary mb-4">Career Strategy & Market Fit</h2><p class="text-gray-600 mb-5">For experienced professionals who want an informed view of where they fit, what to target and how the market is likely to read their profile.</p><ul class="text-sm text-gray-600 space-y-2"><li>✓ Role and level fit</li><li>✓ Career positioning and profile gaps</li><li>✓ Compensation and market perspective where sufficient data exists</li><li>✓ Transition / interview strategy</li><li>✓ Practical next-step plan</li></ul></article><article id="cxo-advisory" class="rounded-[2rem] border-2 border-accent bg-white p-8"><div class="text-accent text-sm font-black mb-2">₹12,500 · 60 MINUTES</div><h2 class="text-3xl font-serif font-bold text-primary mb-4">CXO Strategic Advisory</h2><p class="text-gray-600 mb-5">Confidential decision support for CXOs and senior leaders navigating high-stakes career, role, compensation, transition or positioning decisions.</p><ul class="text-sm text-gray-600 space-y-2"><li>✓ Executive market positioning</li><li>✓ Role/company decision perspective</li><li>✓ Transition and negotiation strategy</li><li>✓ Career-history interpretation</li><li>✓ Senior industry expert involvement where useful</li></ul></article></div>
<div class="rounded-[2rem] bg-primary text-white p-8 md:p-10 mb-10"><div class="text-gold text-xs font-black uppercase tracking-[0.24em] mb-3">Scarce by design</div><h2 class="text-3xl font-serif font-bold mb-4">4 advisory appointments per month.</h2><p class="text-white/75">Maximum one appointment per week, on weekdays between 10:00 AM and 12:00 noon IST. Payment and profile information are required before an advisory request is reviewed.</p></div>
<div class="rounded-[2rem] bg-white border border-gray-200 p-8 md:p-10"><h2 class="text-3xl font-serif font-bold text-primary mb-3">Prepare your advisory request</h2><p class="text-gray-500 mb-7">Use the existing secure HiredNext payment flow first. After payment verification, we will collect the material required for research and appointment review.</p><div class="grid md:grid-cols-2 gap-5 mb-7"><div class="rounded-xl bg-gray-50 p-5"><strong class="text-primary">Required before the session</strong><p class="text-sm text-gray-600 mt-2">CV, LinkedIn URL, current role/company, years of experience, target roles/industries, what you are looking for, and a short brief of the challenge you want solved.</p></div><div class="rounded-xl bg-gray-50 p-5"><strong class="text-primary">For CXO Advisory</strong><p class="text-sm text-gray-600 mt-2">Also tell us the decision you are trying to make and what a successful outcome from the session would look like.</p></div></div><div class="flex flex-wrap gap-3"><a href="<?= base_url('cv-payment/6500') ?>" class="inline-flex px-7 py-3.5 rounded-full bg-accent text-white font-bold">Pay ₹6,500 & Continue →</a><a href="<?= base_url('cv-payment/12500') ?>" class="inline-flex px-7 py-3.5 rounded-full border-2 border-primary text-primary font-bold">Pay ₹12,500 for CXO Advisory →</a></div><p class="mt-5 text-xs text-gray-500">Payment is for professional advisory, not recruitment consideration. HiredNext never charges candidates to apply for jobs or secure placement.</p></div>
<div class="grid md:grid-cols-2 gap-5 mt-8"><div class="rounded-2xl bg-white border p-6"><strong class="text-primary">Have a hiring mandate?</strong><p class="text-sm text-gray-600 my-3">Employer hiring discussions do not carry an advisory fee.</p><a href="<?= base_url('hiring-discussion') ?>" class="font-bold text-primary">Discuss Hiring →</a></div><div class="rounded-2xl bg-white border p-6"><strong class="text-primary">Looking for a job?</strong><p class="text-sm text-gray-600 my-3">Apply to current roles or follow HiredNext Recruitment on LinkedIn. Do not pay for access to a job.</p><a href="<?= base_url('jobs') ?>" class="font-bold text-primary">View Jobs →</a></div></div>
</div></section>
<?= $this->endSection() ?>
